apiVersion: crownlabs.polito.it/v1alpha2
kind: Instance
metadata:
  name: test-multi-env
  namespace: tenant-john-doe
spec:
  template.crownlabs.polito.it/TemplateRef:
    name: multi-env-storage-test
    namespace: tenant-john-doe
  tenant.crownlabs.polito.it/TenantRef:
    name: john-doe